name: Merge up

on:
  push:
    branches:
      - v*.*

permissions:
  contents: write
  pull-requests: write

env:
  GIT_USER_NAME: "147046816+mongodb-drivers-pr-bot[bot]@users.noreply.github.com"
  GIT_USER_EMAIL: "mongodb-drivers-pr-bot[bot]"

jobs:
  merge-up:
    name: Create merge up pull request
    runs-on: ubuntu-latest

    steps:
      - name: "Generate token and checkout repository"
        uses: mongodb-labs/drivers-github-tools/secure-checkout@v2
        with:
          app_id: ${{ vars.MERGE_UP_APP_ID }}
          private_key: ${{ secrets.MERGE_UP_APP_PRIVATE_KEY }}
          # fetch-depth 0 is required to fetch all branches, not just the branch being built
          fetch-depth: 0

      - name: Set git credentials
        run: |
          git config user.email ${GIT_USER_NAME}
          git config user.name ${GIT_USER_EMAIL}

      - name: Create pull request
        uses: alcaeus/automatic-merge-up-action@main
        with:
          ref: ${{ github.ref_name }}
          branchNamePattern: 'v<major>.<minor>'
          fallbackBranch: 'main'
          enableAutoMerge: true
